Create Proposal.md
CSC-480-F2023/group-project-10-days-diary-journaling-app pull request #3
Opened 2023-11-06 14:25 UTC by McGKoe

2023-11-06 14:27 UTC, ecargin1 approved these changes, later dismissed

2023-11-06 14:41 UTC, ecargin1 requested changes
Need to add directory structure

2023-11-06 18:41 UTC, derek-munday requested changes
Not sure what is meant to be reviewed here. What is the DONTREADME.Md file?

2023-11-08 14:55 UTC, closed without merging

2023-11-08 14:55 UTC, ecargin1 commented
Closed - Incorrect/conflicting changes